name: run actions

on: 
  push:
  pull_request:
      types: [closed,opened,reopened]

# https://github.com/actions/hello-world-javascript-action
jobs: 
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - name: write action var
        id: write
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: '输入一个具体的变量到 actions 中'
      - name: print action var
        # 打印这个 actions 中输出的值，一个 actions 不仅可以接受输入，还可以输出
        run: echo "${{ steps.write.outputs.time }}" 
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before ls 
        # $GITHUB_SHA 内置变量 触发此次工作流的 commit id
        # $GITHUB_WORKSPACE 内置变量 虚拟环境下的工作目录
        # $GITHUB_RESPOSITORY 内置变量 当前仓库下名字
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA 
          echo $GITHUB_WORKSPACE
          echo $GITHUB_RESPOSITORY
      - name: checkout branch
        uses: actions/checkout@v3
      - name: checkout after ls 
        run: |
          pwd
          ls -a
   
      
        
     